{{- if .Values.secrets.tailscale.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.networking.tailscale.authSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoocluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_AUTHKEY: {{ .Values.secrets.tailscale.authKey | quote }}
{{- end }}

{{- if .Values.secrets.backup.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.backup.s3.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoocluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.secrets.backup.accessKeyId | quote }}
  SECRET_ACCESS_KEY: {{ .Values.secrets.backup.secretAccessKey | quote }}
{{- end }}

{{- range .Values.secrets.deployKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "odoocluster.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ssh-privatekey: |
    {{- .privateKey | nindent 4 }}
{{- end }}

